name: Linux with 3.9-3.11

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.1
        env:
          CIBW_BUILD: cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y gmp-devel zlib-devel bzip2-devel &&
            python setup.py package_assemble
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: auditwheel repair -w {dest_dir} {wheel}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
